/**
 * @file candidate_generation.h
 * @brief Candidate Generation (Algorithm 4)
 *
 * File này định nghĩa cấu trúc CHash và lớp xử lý để tuân thủ tuyệt đối
 * các bước và tên hàm trong Algorithm 4.
 */

#pragma once

#include "types.h"
#include <vector>
#include <map>
#include <string>

 // ============================================================================
 // CẤU TRÚC DỮ LIỆU C-HASH (Để khớp cú pháp chash[key][f].AddInstances)
 // ============================================================================

 /**
  * @brief Bucket chứa danh sách instance của một feature cụ thể trong pattern
  * Hỗ trợ cú pháp: .AddInstances(cl) (Dòng 6)
  */
struct FeatureBucket {
    std::vector<ColocationInstance> instances;

    /**
     * @brief Thêm một clique vào bucket
     * Tương ứng dòng 6: ...AddInstances(cl)
     */
    void AddInstances(const ColocationInstance& cl) {
        instances.push_back(cl);
    }
};

/**
 * @brief Entry đại diện cho một Key (Pattern), chứa map các Feature
 * Hỗ trợ cú pháp: [f]
 */
struct PatternEntry {
    // Map từ FeatureType ("A", "B") -> Bucket chứa instances
    std::map<FeatureType, FeatureBucket> featureMap;

    /**
     * @brief Truy cập bucket theo feature
     * Tương ứng dòng 6: chash[newKey][f]...
     */
    FeatureBucket& operator[](const FeatureType& f) {
        return featureMap[f];
    }
};

/**
 * @brief Cấu trúc dữ liệu chính c-hash
 * Tương ứng biến 'chash' trong mã giả
 */
struct CHash {
    // Map từ Pattern (Colocation) -> PatternEntry
    // Sử dụng std::map để key (vector<string>) tự động so sánh được
    std::map<Colocation, PatternEntry> data;

    /**
     * @brief Kiểm tra khóa tồn tại
     * Tương ứng dòng 3: If Not chash.ContainsKey(newKey)
     */
    bool ContainsKey(const Colocation& key) const {
        return data.find(key) != data.end();
    }

    /**
     * @brief Khởi tạo key mới
     * Tương ứng dòng 4: chash.AddKeyAndInitialize(NewKey)
     */
    void AddKeyAndInitialize(const Colocation& key) {
        // Truy cập vào key sẽ tự động tạo entry mặc định trong std::map
        // Nhưng để đúng tên hàm, ta wrap lại:
        data[key];
    }

    /**
     * @brief Truy cập PatternEntry theo key
     * Tương ứng dòng 6: chash[newKey]...
     */
    PatternEntry& operator[](const Colocation& key) {
        return data[key];
    }
};

// ============================================================================
// LỚP THỰC THI THUẬT TOÁN
// ============================================================================

class CandidateGenerator {
private:
    // ========================================================================
    // CÁC HÀM HELPERS (Tuân thủ tên trong Algorithm 4)
    // ========================================================================

    /**
     * @brief Lấy tập các feature của một clique làm key
     * Tương ứng dòng 2: newKey = GetFeatures(cl)
     * Logic: Trích xuất feature type từ từng instance trong cl và sắp xếp lại.
     */
    Colocation GetFeatures(const ColocationInstance& cl) const;

public:
    /**
     * @brief Thực thi thuật toán Candidate Generation
     * * Input: cls (Cliques generated by IDS or NDS)
     * Output: chash (c-hash structure)
     * * @param cls Danh sách các clique đầu vào
     * @return CHash Cấu trúc c-hash đã được xây dựng
     */
    CHash generate(const std::vector<ColocationInstance>& cls);
};